name: Update Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-readme:
    name: Update Profile README with Latest Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with latest activity
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_OS: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE_PER_REPO: "True"

      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Updated README with latest stats" -a || exit 0
          git push
